USE ECOMMERCE_BUSINESS;

CREATE TABLE IF NOT EXISTS Product_Store (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    store_id INT UNSIGNED NOT NULL,
    product_id INT UNSIGNED NOT NULL
    current_stock INT UNSIGNED,
    current_price INT UNSIGNED NULL,
    current_disccount INT UNSIGNED NULL,
    FOREIGN KEY (store_id) REFERENCES Stores(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES Products(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Account_Address (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    account_id INT UNSIGNED NOT NULL,
    street VARCHAR(255) NOT NULL,
    number INT UNSIGNED,
    unit VARCHAR(255),
    city VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    FOREIGN KEY (account_id) REFERENCES Accounts(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Account_Order (
    id INT UNSIGNED NOT NULL PRIMARY KEY,
    account_id INT UNSIGNED NOT NULL,
    address_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (account_id) REFERENCES Accounts(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    FOREIGN KEY (address_id) REFERENCES Account_Address(id)
);