CREATE DATABASE IF NOT EXISTS ECOMMERCE_BUSINESS;

USE ECOMMERCE_BUSINESS;

CREATE TABLE IF NOT EXISTS Users (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL
    );

CREATE TABLE IF NOT EXISTS Accounts (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (user_id) REFERENCES Users(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Stores (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    name VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (user_id) REFERENCES Users(id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Products (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT
);

CREATE TABLE IF NOT EXISTS Orders (
    id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    invoice INT UNSIGNED NOT NULL,
    total_price INT UNSIGNED NOT NULL,
    processing tinyint DEFAULT(1),
    sent tinyint DEFAULT(0),
    delivered tinyint DEFAULT(0),
    cancelled tinyint DEFAULT(0),
    INDEX(invoice)
);

